title: Мой архив ВКонтакте
description: Личная стена
url: https://boris43389.github.io
baseurl: /Whitel_Dragon
google_cx: "7379b4ee9cbbd4769"
ga4: "G-BTYZWTGBN6"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 10              # по 10 постов на страницу
paginate_path: "/page:num/"
