title: Мой архив ВКонтакте (в разработке v0.3)
description: Личная стена
url: https://boris43389.github.io
baseurl: /Whitel_Dragon
google_cx: "7379b4ee9cbbd4769"
ga4: "G-KX2LDCQ32L"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 10              # по 10 постов на страницу
paginate_path: "/page:num/"

